// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class DireTideCustomGameHeroWinDayTypeQueryBuilder : GraphQlQueryBuilder<DireTideCustomGameHeroWinDayTypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
            new []
            {
                new GraphQlFieldMetadata { Name = "day" },
                new GraphQlFieldMetadata { Name = "heroId" },
                new GraphQlFieldMetadata { Name = "winCount" },
                new GraphQlFieldMetadata { Name = "matchCount" },
                new GraphQlFieldMetadata { Name = "candyScored" }
            };

        protected override string TypeName { get { return "DireTideCustomGameHeroWinDayType"; } } 

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public DireTideCustomGameHeroWinDayTypeQueryBuilder WithDay(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("day", alias, new GraphQlDirective[] { include, skip });
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder ExceptDay()
        {
            return ExceptField("day");
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder WithHeroId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("heroId", alias, new GraphQlDirective[] { include, skip });
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder ExceptHeroId()
        {
            return ExceptField("heroId");
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder WithWinCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("winCount", alias, new GraphQlDirective[] { include, skip });
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder ExceptWinCount()
        {
            return ExceptField("winCount");
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder WithMatchCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("matchCount", alias, new GraphQlDirective[] { include, skip });
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder ExceptMatchCount()
        {
            return ExceptField("matchCount");
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder WithCandyScored(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("candyScored", alias, new GraphQlDirective[] { include, skip });
        }

        public DireTideCustomGameHeroWinDayTypeQueryBuilder ExceptCandyScored()
        {
            return ExceptField("candyScored");
        }
    }
}
