// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroPositionTimeDetailType
    {
        public short? HeroId { get; set; }
        public int? Week { get; set; }
        public int? Time { get; set; }
        public MatchPlayerPositionType? Position { get; set; }
        public RankBracketBasicEnum? BracketBasicIds { get; set; }
        public long? MatchCount { get; set; }
        public long? RemainingMatchCount { get; set; }
        public long? WinCount { get; set; }
        public double? Mvp { get; set; }
        public double? TopCore { get; set; }
        public double? TopSupport { get; set; }
        public double? CourierKills { get; set; }
        public double? Apm { get; set; }
        public double? Casts { get; set; }
        public double? AbilityCasts { get; set; }
        public double? Kills { get; set; }
        public double? Deaths { get; set; }
        public double? Assists { get; set; }
        public double? Networth { get; set; }
        public double? Xp { get; set; }
        public double? Cs { get; set; }
        public double? Dn { get; set; }
        public double? Neutrals { get; set; }
        public double? HeroDamage { get; set; }
        public double? TowerDamage { get; set; }
        public double? PhysicalDamage { get; set; }
        public double? MagicalDamage { get; set; }
        public double? PhysicalDamageReceived { get; set; }
        public double? MagicalDamageReceived { get; set; }
        public double? TripleKill { get; set; }
        public double? UltraKill { get; set; }
        public double? Rampage { get; set; }
        public double? GodLike { get; set; }
        public double? GoldPerMinute { get; set; }
        public double? DisableCount { get; set; }
        public double? DisableDuration { get; set; }
        public double? StunCount { get; set; }
        public double? StunDuration { get; set; }
        public double? SlowCount { get; set; }
        public double? SlowDuration { get; set; }
        public double? HealingSelf { get; set; }
        public double? HealingAllies { get; set; }
        public double? InvisibleCount { get; set; }
        public double? RunePower { get; set; }
        public double? RuneBounty { get; set; }
        public double? Level { get; set; }
        public double? CampsStacked { get; set; }
        public double? SupportGold { get; set; }
        public double? PurgeModifiers { get; set; }
        public double? Ancients { get; set; }
        public double? TeamKills { get; set; }
        public double? GoldLost { get; set; }
        public double? GoldFed { get; set; }
        public double? BuybackCount { get; set; }
        public double? WeakenCount { get; set; }
        public double? WeakenDuration { get; set; }
        public double? PhysicalItemDamage { get; set; }
        public double? MagicalItemDamage { get; set; }
        public double? HealingItemSelf { get; set; }
        public double? HealingItemAllies { get; set; }
        public double? XpFed { get; set; }
        public double? PureDamageReceived { get; set; }
        public double? AttackDamage { get; set; }
        public double? AttackCount { get; set; }
        public double? CastDamage { get; set; }
        public double? DamageReceived { get; set; }
        public double? Damage { get; set; }
        public double? PureDamage { get; set; }
        public double? KdaAverage { get; set; }
        public double? KillContributionAverage { get; set; }
        public double? StompWon { get; set; }
        public double? StompLost { get; set; }
        public double? ComeBackWon { get; set; }
        public double? ComeBackLost { get; set; }
    }
}
