// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroRoleTypeQueryBuilder : GraphQlQueryBuilder<HeroRoleTypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
            new []
            {
                new GraphQlFieldMetadata { Name = "roleId" },
                new GraphQlFieldMetadata { Name = "level" }
            };

        protected override string TypeName { get { return "HeroRoleType"; } } 

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public HeroRoleTypeQueryBuilder WithRoleId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("roleId", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroRoleTypeQueryBuilder ExceptRoleId()
        {
            return ExceptField("roleId");
        }

        public HeroRoleTypeQueryBuilder WithLevel(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("level", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroRoleTypeQueryBuilder ExceptLevel()
        {
            return ExceptField("level");
        }
    }
}
