// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class ImpGeneratorRequestType : IGraphQlInputObject
    {
        private InputPropertyInfo _bans;
        private InputPropertyInfo _players;
        private InputPropertyInfo _isTurbo;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<short>>))]
        #endif
        public QueryBuilderParameter<ICollection<short>> Bans
        {
            get { return (QueryBuilderParameter<ICollection<short>>)_bans.Value; }
            set { _bans = new InputPropertyInfo { Name = "bans", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<ImpGeneratorPlayerRequestType>>))]
        #endif
        public QueryBuilderParameter<ICollection<ImpGeneratorPlayerRequestType>> Players
        {
            get { return (QueryBuilderParameter<ICollection<ImpGeneratorPlayerRequestType>>)_players.Value; }
            set { _players = new InputPropertyInfo { Name = "players", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        public QueryBuilderParameter<bool?> IsTurbo
        {
            get { return (QueryBuilderParameter<bool?>)_isTurbo.Value; }
            set { _isTurbo = new InputPropertyInfo { Name = "isTurbo", Value = value }; }
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_bans.Name != null) yield return _bans;
            if (_players.Name != null) yield return _players;
            if (_isTurbo.Name != null) yield return _isTurbo;
        }
    }
}
