// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchPlayerStatsItemUsedEventTypeQueryBuilder : GraphQlQueryBuilder<MatchPlayerStatsItemUsedEventTypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
            new []
            {
                new GraphQlFieldMetadata { Name = "itemId" },
                new GraphQlFieldMetadata { Name = "count" }
            };

        protected override string TypeName { get { return "MatchPlayerStatsItemUsedEventType"; } } 

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public MatchPlayerStatsItemUsedEventTypeQueryBuilder WithItemId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("itemId", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsItemUsedEventTypeQueryBuilder ExceptItemId()
        {
            return ExceptField("itemId");
        }

        public MatchPlayerStatsItemUsedEventTypeQueryBuilder WithCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("count", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsItemUsedEventTypeQueryBuilder ExceptCount()
        {
            return ExceptField("count");
        }
    }
}
