// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchPlayerStatsHeroDamageReportType
    {
        public MatchPlayerHeroDamageTotalReportObjectType DealtTotal { get; set; }
        public MatchPlayerHeroDamageTotalRecievedReportObjectType ReceivedTotal { get; set; }
        public ICollection<MatchPlayerHeroDamageTargetReportObjectType> DealtTargets { get; set; }
        public ICollection<MatchPlayerHeroDamageTargetReportObjectType> ReceivedTargets { get; set; }
        public ICollection<MatchPlayerHeroDamageSourceAbilityReportObjectType> DealtSourceAbility { get; set; }
        public ICollection<MatchPlayerHeroDamageSourceAbilityReportObjectType> ReceivedSourceAbility { get; set; }
        public ICollection<MatchPlayerHeroDamageSourceItemReportObjectType> DealtSourceItem { get; set; }
        public ICollection<MatchPlayerHeroDamageSourceItemReportObjectType> ReceivedSourceItem { get; set; }
    }
}
