// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchPlayerStatsDeathEventTypeQueryBuilder : GraphQlQueryBuilder<MatchPlayerStatsDeathEventTypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
            new []
            {
                new GraphQlFieldMetadata { Name = "time" },
                new GraphQlFieldMetadata { Name = "attacker" },
                new GraphQlFieldMetadata { Name = "target" },
                new GraphQlFieldMetadata { Name = "byAbility" },
                new GraphQlFieldMetadata { Name = "byItem" },
                new GraphQlFieldMetadata { Name = "goldFed" },
                new GraphQlFieldMetadata { Name = "xpFed" },
                new GraphQlFieldMetadata { Name = "timeDead" },
                new GraphQlFieldMetadata { Name = "positionX" },
                new GraphQlFieldMetadata { Name = "positionY" },
                new GraphQlFieldMetadata { Name = "goldLost" },
                new GraphQlFieldMetadata { Name = "assist", IsComplex = true },
                new GraphQlFieldMetadata { Name = "isWardWalkThrough" },
                new GraphQlFieldMetadata { Name = "isAttemptTpOut" },
                new GraphQlFieldMetadata { Name = "isDieBack" },
                new GraphQlFieldMetadata { Name = "isBurst" },
                new GraphQlFieldMetadata { Name = "isEngagedOnDeath" },
                new GraphQlFieldMetadata { Name = "hasHealAvailable" },
                new GraphQlFieldMetadata { Name = "isTracked" }
            };

        protected override string TypeName { get { return "MatchPlayerStatsDeathEventType"; } } 

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithTime(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("time", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptTime()
        {
            return ExceptField("time");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithAttacker(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("attacker", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptAttacker()
        {
            return ExceptField("attacker");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithTarget(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("target", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptTarget()
        {
            return ExceptField("target");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithByAbility(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("byAbility", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptByAbility()
        {
            return ExceptField("byAbility");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithByItem(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("byItem", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptByItem()
        {
            return ExceptField("byItem");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithGoldFed(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("goldFed", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptGoldFed()
        {
            return ExceptField("goldFed");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithXpFed(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("xpFed", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptXpFed()
        {
            return ExceptField("xpFed");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithTimeDead(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("timeDead", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptTimeDead()
        {
            return ExceptField("timeDead");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithPositionX(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("positionX", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptPositionX()
        {
            return ExceptField("positionX");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithPositionY(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("positionY", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptPositionY()
        {
            return ExceptField("positionY");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithGoldLost(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("goldLost", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptGoldLost()
        {
            return ExceptField("goldLost");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithAssist(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("assist", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptAssist()
        {
            return ExceptField("assist");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithIsWardWalkThrough(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("isWardWalkThrough", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptIsWardWalkThrough()
        {
            return ExceptField("isWardWalkThrough");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithIsAttemptTpOut(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("isAttemptTpOut", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptIsAttemptTpOut()
        {
            return ExceptField("isAttemptTpOut");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithIsDieBack(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("isDieBack", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptIsDieBack()
        {
            return ExceptField("isDieBack");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithIsBurst(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("isBurst", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptIsBurst()
        {
            return ExceptField("isBurst");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithIsEngagedOnDeath(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("isEngagedOnDeath", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptIsEngagedOnDeath()
        {
            return ExceptField("isEngagedOnDeath");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithHasHealAvailable(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("hasHealAvailable", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptHasHealAvailable()
        {
            return ExceptField("hasHealAvailable");
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder WithIsTracked(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("isTracked", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsDeathEventTypeQueryBuilder ExceptIsTracked()
        {
            return ExceptField("isTracked");
        }
    }
}
