// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchPlayerLivePlaybackDataType
    {
        public ICollection<MatchLivePlayerPositionDetailType> PositionEvents { get; set; }
        public ICollection<MatchLivePlayerGoldDetailType> GoldEvents { get; set; }
        public ICollection<MatchLivePlayerLevelDetailType> LevelEvents { get; set; }
        public ICollection<MatchLivePlayerKillDetailType> KillEvents { get; set; }
        public ICollection<MatchLivePlayerDeathDetailType> DeathEvents { get; set; }
        public ICollection<MatchLivePlayerAssistDetailType> AssistEvents { get; set; }
        public ICollection<MatchLivePlayerLastHitDetailType> CsEvents { get; set; }
        public ICollection<MatchLivePlayerDenyDetailType> DenyEvents { get; set; }
        public ICollection<MatchLivePlayerExperienceDetailType> ExperienceEvents { get; set; }
        public ICollection<MatchLivePlayerInventoryDetailType> InventoryEvents { get; set; }
    }
}
