// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PageMatchesQuery
    {
        public ICollection<MatchesHourType> MatchesStatsHour { get; set; }
        public ICollection<MatchesDayType> MatchesStatsDay { get; set; }
        public ICollection<MatchesWeekType> MatchesStatsWeek { get; set; }
        public ICollection<MatchesMonthType> MatchesStatsMonth { get; set; }
        public ICollection<MatchesGameVersionType> MatchesStatsGameVersion { get; set; }
        public ICollection<MatchmakingStatsType> MatchmakingStats { get; set; }
    }
}
