// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PlayerType
    {
        public long? SteamAccountId { get; set; }
        public CaptainJackIdentityPublicProfileType Identity { get; set; }
        public SteamAccountType SteamAccount { get; set; }
        public int? MatchCount { get; set; }
        public int? WinCount { get; set; }
        public int? Imp { get; set; }
        public long? FirstMatchDate { get; set; }
        public long? LastMatchDate { get; set; }
        public byte? LastMatchRegionId { get; set; }
        public ICollection<SteamAccountSeasonRankType> Ranks { get; set; }
        public ICollection<SteamAccountSeasonLeaderBoardRankType> LeaderboardRanks { get; set; }
        public ICollection<PlayerBadgeType> Badges { get; set; }
        public ICollection<SteamAccountNameType> Names { get; set; }
        public short? BehaviorScore { get; set; }
        public SteamAccountTeamMemberType Team { get; set; }
        public GuildMemberType GuildMember { get; set; }
        public PlayerActivitySummaryType Activity { get; set; }
        public bool? IsFollowed { get; set; }
        public PlayerCardHoverType SimpleSummary { get; set; }
        public PlayerPerformanceType Performance { get; set; }
        public PlayerPerformanceType HeroPerformance { get; set; }
        public ICollection<PlayerHeroesPerformanceType> HeroesPerformance { get; set; }
        public ICollection<MatchType> Matches { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(GraphQlInterfaceJsonConverter))]
        #endif
        public ICollection<IMatchGroupByType> MatchesGroupBy { get; set; }
        public ICollection<HeroDotaPlusLeaderboardRankType> DotaPlus { get; set; }
        public ICollection<PlayerHeroPerformanceLongestStreakType> HeroStreaks { get; set; }
        public ICollection<FeatType> Feats { get; set; }
    }
}
