// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PlayerDraftHeroHighlightTypeQueryBuilder : GraphQlQueryBuilder<PlayerDraftHeroHighlightTypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
            new []
            {
                new GraphQlFieldMetadata { Name = "lastPlayed" },
                new GraphQlFieldMetadata { Name = "winCount" },
                new GraphQlFieldMetadata { Name = "matchCount" },
                new GraphQlFieldMetadata { Name = "impAllTime" },
                new GraphQlFieldMetadata { Name = "mvpCountLastMonth" },
                new GraphQlFieldMetadata { Name = "topCoreCountLastMonth" },
                new GraphQlFieldMetadata { Name = "topSupportCountLastMonth" },
                new GraphQlFieldMetadata { Name = "winCountLastMonth" },
                new GraphQlFieldMetadata { Name = "matchCountLastMonth" },
                new GraphQlFieldMetadata { Name = "impLastMonth" },
                new GraphQlFieldMetadata { Name = "winCountLastSixMonths" },
                new GraphQlFieldMetadata { Name = "matchCountLastSixMonths" },
                new GraphQlFieldMetadata { Name = "impLastSixMonths" }
            };

        protected override string TypeName { get { return "PlayerDraftHeroHighlightType"; } } 

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public PlayerDraftHeroHighlightTypeQueryBuilder WithLastPlayed(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("lastPlayed", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptLastPlayed()
        {
            return ExceptField("lastPlayed");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithWinCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("winCount", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptWinCount()
        {
            return ExceptField("winCount");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithMatchCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("matchCount", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptMatchCount()
        {
            return ExceptField("matchCount");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithImpAllTime(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("impAllTime", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptImpAllTime()
        {
            return ExceptField("impAllTime");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithMvpCountLastMonth(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("mvpCountLastMonth", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptMvpCountLastMonth()
        {
            return ExceptField("mvpCountLastMonth");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithTopCoreCountLastMonth(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("topCoreCountLastMonth", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptTopCoreCountLastMonth()
        {
            return ExceptField("topCoreCountLastMonth");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithTopSupportCountLastMonth(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("topSupportCountLastMonth", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptTopSupportCountLastMonth()
        {
            return ExceptField("topSupportCountLastMonth");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithWinCountLastMonth(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("winCountLastMonth", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptWinCountLastMonth()
        {
            return ExceptField("winCountLastMonth");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithMatchCountLastMonth(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("matchCountLastMonth", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptMatchCountLastMonth()
        {
            return ExceptField("matchCountLastMonth");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithImpLastMonth(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("impLastMonth", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptImpLastMonth()
        {
            return ExceptField("impLastMonth");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithWinCountLastSixMonths(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("winCountLastSixMonths", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptWinCountLastSixMonths()
        {
            return ExceptField("winCountLastSixMonths");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithMatchCountLastSixMonths(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("matchCountLastSixMonths", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptMatchCountLastSixMonths()
        {
            return ExceptField("matchCountLastSixMonths");
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder WithImpLastSixMonths(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("impLastSixMonths", alias, new GraphQlDirective[] { include, skip });
        }

        public PlayerDraftHeroHighlightTypeQueryBuilder ExceptImpLastSixMonths()
        {
            return ExceptField("impLastSixMonths");
        }
    }
}
