// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PlusHeroTeamStatusAveragesType
    {
        public double? Cs { get; set; }
        public double? Deaths { get; set; }
        public double? TowerDamage { get; set; }
        public double? PhysicalDamage { get; set; }
        public double? MagicalDamage { get; set; }
        public double? PhysicalDamageReceived { get; set; }
        public double? MagicalDamageReceived { get; set; }
        public double? DisableCount { get; set; }
        public double? DisableDuration { get; set; }
        public double? StunCount { get; set; }
        public double? StunDuration { get; set; }
        public double? SlowCount { get; set; }
        public double? SlowDuration { get; set; }
        public double? HealingAllies { get; set; }
        public double? PurgeModifiers { get; set; }
        public double? WeakenCount { get; set; }
        public double? WeakenDuration { get; set; }
        public double? PureDamageReceived { get; set; }
        public double? PureDamage { get; set; }
    }
}
