// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PlusHoverBanTypeQueryBuilder : GraphQlQueryBuilder<PlusHoverBanTypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
            new []
            {
                new GraphQlFieldMetadata { Name = "heroId" },
                new GraphQlFieldMetadata { Name = "score" },
                new GraphQlFieldMetadata { Name = "flags" }
            };

        protected override string TypeName { get { return "PlusHoverBanType"; } } 

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public PlusHoverBanTypeQueryBuilder WithHeroId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("heroId", alias, new GraphQlDirective[] { include, skip });
        }

        public PlusHoverBanTypeQueryBuilder ExceptHeroId()
        {
            return ExceptField("heroId");
        }

        public PlusHoverBanTypeQueryBuilder WithScore(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("score", alias, new GraphQlDirective[] { include, skip });
        }

        public PlusHoverBanTypeQueryBuilder ExceptScore()
        {
            return ExceptField("score");
        }

        public PlusHoverBanTypeQueryBuilder WithFlags(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("flags", alias, new GraphQlDirective[] { include, skip });
        }

        public PlusHoverBanTypeQueryBuilder ExceptFlags()
        {
            return ExceptField("flags");
        }
    }
}
