// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class SearchType
    {
        public ICollection<SteamAccountType> Players { get; set; }
        public ICollection<MatchType> Matches { get; set; }
        public ICollection<LeagueType> Leagues { get; set; }
        public ICollection<TeamType> Teams { get; set; }
        public ICollection<SteamAccountType> ProPlayers { get; set; }
        public ICollection<SteamAccountType> Casters { get; set; }
        public GuildType Guild { get; set; }
        public ICollection<DireTideCustomGameMatchType> DireTideMatches { get; set; }
    }
}
