// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class SteamAccountBattlePassTypeQueryBuilder : GraphQlQueryBuilder<SteamAccountBattlePassTypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
            new []
            {
                new GraphQlFieldMetadata { Name = "steamAccountId" },
                new GraphQlFieldMetadata { Name = "eventId" },
                new GraphQlFieldMetadata { Name = "level" }
            };

        protected override string TypeName { get { return "SteamAccountBattlePassType"; } } 

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public SteamAccountBattlePassTypeQueryBuilder WithSteamAccountId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("steamAccountId", alias, new GraphQlDirective[] { include, skip });
        }

        public SteamAccountBattlePassTypeQueryBuilder ExceptSteamAccountId()
        {
            return ExceptField("steamAccountId");
        }

        public SteamAccountBattlePassTypeQueryBuilder WithEventId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("eventId", alias, new GraphQlDirective[] { include, skip });
        }

        public SteamAccountBattlePassTypeQueryBuilder ExceptEventId()
        {
            return ExceptField("eventId");
        }

        public SteamAccountBattlePassTypeQueryBuilder WithLevel(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("level", alias, new GraphQlDirective[] { include, skip });
        }

        public SteamAccountBattlePassTypeQueryBuilder ExceptLevel()
        {
            return ExceptField("level");
        }
    }
}
